swagger: "2.0"
info:
  version: "1.0.0"
  title: "Gate Control API"
  description: "API for controlling barrier gates"
host: "localhost:8080"
basePath: "/"
schemes:
  - "http"

paths:
  /open:
    post:
      summary: "Open the barrier gate"
      description: "Opens the barrier gate if the cooldown period has expired"
      tags:
        - "barrier"
      responses:
        200:
          description: "Barrier gate handled successfully"
        500:
          description: "Internal server error"

  /metrics:
    get:
      summary: "Get service metrics"
      description: "Returns current service metrics including RPS and blocked requests"
      tags:
        - "metrics"
      responses:
        200:
          description: "Metrics retrieved successfully"
          schema:
            type: "object"
            properties:
              rps:
                type: "number"
                format: "float"
              daily_blocked:
                type: "integer"
              last_reset:
                type: "string"
                format: "date-time"

  /swagger/{any}:
    x-swagger-router-controller: "swagger"
    get:
      summary: "Swagger UI"
      description: "Serves the Swagger UI"
      tags:
        - "documentation"
      produces:
        - "text/html"
      responses:
        200:
          description: "Swagger UI"