name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Swagger CLI
      run: |
        go install github.com/swaggo/swag/cmd/swag@latest

    - name: Generate Swagger Docs
      run: |
        swag init --dir . --output docs

    - name: Lint
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        goimports -w -l .
        go vet ./...

    - name: Test
      run: |
        go test ./... -cover

    - name: Build binary
      run: go build -o gate-service

    - name: Build Docker image
      run: |
        docker build -t your-dockerhub/gate-service:latest .

    - name: Push to Docker Hub
      run: |
        docker push your-dockerhub/gate-service:latest
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      if: github.ref == 'refs/heads/main'