name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        version: 1.24
        
    - name: Install dependencies
      run: |
        go mod download
        
    - name: Build
      run: |
        make build
        
    - name: Test
      run: |
        make test
        
    - name: Lint
      run: |
        make lint

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: my-docker-hub/${{ github.repository }}:latest
        build-args: |
          VERSION=${{ github.sha }}